#! /bin/bash
IF=enp12s0u1
touch /tmp/procnetstatsrx
touch /tmp/procnetstatstx
i=0
while true;
do
    f=$(cat /sys/class/thermal/thermal_zone0/temp)
    t=$(echo $f | cut -b -2).$(echo $f | cut -b 3-)°C
    d=$(date '+%a %b %d, %H:%M:%S')
    w=$(w | head -1)
    mem=$(free -m|grep -e ^Mem)
    total=$(echo $mem|awk '{print $2;}'|numfmt --to si --from-unit=M --format "%2.2f")
    free=$(echo $mem|awk '{print $3;}'|numfmt --to si --from-unit=M --format "%2.2f")
    used=$(echo $mem|awk '{print $4;}'|numfmt --to si --from-unit=M --format "%2.2f")
    freq=$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq | numfmt --to=iec-i --from-unit=K | tr "\n" " ")
    # set -x
    rxold=$(cat /tmp/procnetstatsrx)
    rx=$(cat /proc/net/dev | grep ${IF} | awk '{print $2;}' | tee /tmp/procnetstatsrx)
    rxdelta=$(expr $rx - $rxold | numfmt --to si)
    txold=$(cat /tmp/procnetstatstx)
    tx=$(cat /proc/net/dev | grep ${IF} | awk '{print $10;}' | tee /tmp/procnetstatstx)
    txdelta=$(expr $tx - $txold | numfmt --to si)
    if [ $i == 5 ]; then
    	hetzner=$(ssh hetzner2 w | grep load | cut -f 5 -d ":")
	i=0
    fi
    # set +x
    xsetroot -name "hetzner: $hetzner | $w | $freq | t/f/u $total/$free/$used | rx/tx $rxdelta/$txdelta | $d | $t"
    sleep 1
    i=$(( $i + 1 ))
done
